name: rainforest
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - dataclasses=0.8
  - pytorch=1.9.0
  - pytorch-lightning=1.4.5
  - torchaudio=0.9.0
  - torchmetrics=0.5.1
  - torchvision=0.10.0